- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
    - id: flake8
      args:
        - --max-line-length=120
    - id: check-docstring-first
    - id: debug-statements
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.4.0
  hooks:
    - id: reorder-python-imports
      language_version: python3
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      files: \.py$
      args: [--rcfile=.pylintrc, --load-plugins=pylint_flask]
