- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: flake8
      args:
        - --max-line-length=120
    - id: check-docstring-first
    - id: debug-statements
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.3
  hooks:
    - id: autopep8
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.5
  hooks:
    - id: reorder-python-imports
      language_version: python3
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.2.2
  hooks:
    - id: pylint
      args:
        - --rcfile=./.pylintrc